//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesHomes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITMHousingSalesEntities : DbContext
    {
        public ITMHousingSalesEntities()
            : base("name=ITMHousingSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Housing> Housing { get; set; }
        public virtual DbSet<HousingType> HousingType { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
    }
}
